 providers = ['node', 'python']

  [phases.setup]
  nixPkgs = ['...', 'python312', 'nodejs', 'gcc', 'gnumake', 'pkg-config']
  aptPkgs = ['build-essential', 'libudev-dev']

  [phases.install]
  cmds = ['npm install node-gyp -g', 'npm ci']

  [start]
  cmd = 'npm start'
